stages:
  - lints
  - test
  - build
  - beta

variables:
  FLUTTER_VERSION: "3.13.9"
  FASTLANE_LANE: "beta"

analyze:
  stage: lints
  image: "ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION"
  script:
    - flutter analyze

unit test:
  stage: test
  image: "ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION"
  before_script:
    - flutter pub global activate junitreport
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - coverage
    reports:
      junit: report.xml

android:
  stage: build
  image: "ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION"
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/

ios:
  stage: build
  image: "ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION"
  script:
    # - flutter build ios --release
    - echo "Mock Build IPA"
  # artifacts:
  #   paths:
  #     - build/ios/iphoneos/Runner.app # Adjust the path to the .ipa file
  #     - build/ios/ipa_archive/*.ipa  # Include the .ipa file if generated by Flutter
  #   expire_in: 1 week  # Adjust the expiration time as needed

beta:
  stage: beta
  only:
    - master  # Run only on the master branch
  script:
    - echo "Deploy to Firebase for Beta testing"
    # Add commands to deploy to Firebase for Beta testing
