# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    firebase_app_distribution(
          app: "1:836483067210:android:2288c8881bd8fab3bae5b3",
          # testers: "anupong.niceone@gmail.com",
          release_notes: "Beta test",
          # apk_path: "",
          # firebase_cli_token: "",
          firebase_cli_token: ENV["FIREBASE_TOKEN"],
      )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :buildNumber do
    lastNum = latest_testflight_build_number + 1
    filename = "../../pubspec.yaml"
    outdata = File.read(filename).gsub(/version: \d+\.\d+\.\d+\+\d+/, "version: 0.1.0+#{lastNum}")
    File.open(filename, 'w') do |out|
      out << outdata
    end
  end

  # lane :increment_version do
  #   latest_release = firebase_app_distribution_get_latest_release(
  #     app: "<your Firebase app ID>"
  #   )
  #   increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
